# Generated by Django 5.1 on 2024-08-10 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_bus_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 10, 12, 40, 32, 597846, tzinfo=datetime.timezone.utc)),
        ),
    ]
