# Generated by Django 5.1 on 2024-08-10 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_bus_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 10, 16, 41, 29, 75941, tzinfo=datetime.timezone.utc)),
        ),
    ]
